# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ced9f75848fa580dd4d964d959d4c5d81a1eb88ec6317d34075e39f63df2c4bccc150e71c5289feb934d18a3f80ebe36ae42d36ddd40a65a66ca8534298c74

test:
  secret_key_base: ea49d225e6f4c0cf14724a043359170a4f2aa07d8e70cc771299b9c284fbc102f16db98894da63830b7445c6e4bf539254d7d1f90c0b00170da82196bbc62078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
